services:
  app:
    build: ./app
    volumes:
      - ./app/src:/service/src
    environment:
      - MONGO_URI=mongodb://mongodb:27017
      - DEFAULT_BATCH_SIZE=10

    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb:/data/db

volumes:
  mongodb: